[project]
name = "thcoburg-projecte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "httpx>=0.28.1",
    "icecream>=2.2.0",
    "pydantic[email]>=2.13.3",
    "pytest>=9.0.3",
    "requests>=2.34.2",
    "sqlmodel>=0.0.38",
    "streamlit>=1.57.0",
]
